# Fourth plot: lattice of 4 plots of the Household power consumption data
# on the days 2007-02-01 to 2007-02-02

# setwd("D:/workspace/DataScienceSpecial/EDA/assessment1/ExData_Plotting1")
# Use data.table instead of data.frame
library(data.table)

# read the whole data on file
electric <- fread("../household_power_consumption.txt", na.strings='?')

# subselect the data for the days 2007-02-01 to 2007-02-02
el <- electric[Date=='1/2/2007' | Date=='2/2/2007']

# coerce the column 'Global_active_power' from char to numeric in order to plot frequencies
el[, Global_active_power := as.numeric(Global_active_power)]

# coerce the column 'Voltage' from char to numeric in order to plot frequencies
el[, Voltage := as.numeric(Voltage)]

# create a new column with a full date as POSIXct
# for some reason, the POSIXlt generated by strptime raises an error when assigned to a column of the data.table!
# circumvented the problem by converting POSIXlt to POSIXct
el[, dateTime := as.POSIXct(strptime(paste(el$Date, el$Time), "%d/%m/%Y %H:%M:%S"))]

# coerce the submetering columns from char to numeric to be able to plot them
el[, Sub_metering_1 := as.numeric(Sub_metering_1)]
el[, Sub_metering_2 := as.numeric(Sub_metering_2)]

# coerce the column 'Global_reactive_power' from char to numeric in order to plot frequencies
el[, Global_reactive_power := as.numeric(Global_reactive_power)]

# Frame for 2 by 2 plots
par(mfrow=c(2,2))

# First scatter plot - Global Active Power: points are linked by lines (type='l')
plot(el$Global_active_power ~ el$dateTime, type='l', ylab='Global Active Power', xlab='')

# First scatter plot - Global Active Power: points are linked by lines (type='l')
plot(el$Global_active_power ~ el$dateTime, type='l', ylab='Global Active Power', xlab='')

# Second scatter plot - Voltage: points are linked by lines (type='l')
plot(el$Voltage ~ el$dateTime, type='l', xlab='datetime', ylab='Voltage')

# Third scatter plot - Submetering: points are linked by lines (type='l')
plot(el$Sub_metering_1 ~ el$dateTime, type='l', ylab='Energy sub metering', xlab='')
points(el$Sub_metering_2 ~ el$dateTime, col='red', type='l')
points(el$Sub_metering_3 ~ el$dateTime, col='blue', type='l')
legend("topright", lty=1, lwd=2, col=c('black', 'red', 'blue'), legend=names(el)[7:9], bty='n')

# Fourth scatter plot - Global Reactive Power: points are linked by lines (type='l')
plot(el$Global_reactive_power ~ el$dateTime, type='l', ylab='Global_reactive_power', xlab='datetime')

# Copy the plot to the PNG file device
dev.copy(png, file="plot4.png")
dev.off()
