# Second plot: line plot of the variable 'Global_active_power' for the Household power consumption data
# on the days 2007-02-01 to 2007-02-02

# setwd("D:/workspace/DataScienceSpecial/EDA/assessment1/ExData_Plotting1")
# Use data.table instead of data.frame
library(data.table)

# Fixes locale so that the week days appear in english
Sys.setlocale(category = "LC_ALL", locale = "English_United States.1252")

# read the whole data on file
electric <- fread("../household_power_consumption.txt", na.strings='?')

# subselect the data for the days 2007-02-01 to 2007-02-02
el <- electric[Date=='1/2/2007' | Date=='2/2/2007']

# create a new column with a full date as POSIXct
# for some reason, the POSIXlt generated by strptime raises an error when assigned to a column of the data.table!
# circumvented the problem by converting POSIXlt to POSIXct
el[, dateTime := as.POSIXct(strptime(paste(el$Date, el$Time), "%d/%m/%Y %H:%M:%S"))]

# coerce the column 'Global_active_power' from char to numeric to be able to plot
el[, Global_active_power := as.numeric(Global_active_power)]

# scatter plot: points are linked by lines (type='l')
plot(el$Global_active_power ~ el$dateTime, type='l', ylab='Global Active Power (kilowatts)', xlab='')

# Copy the plot to the PNG file device
dev.copy(png, file="plot2.png", width=480, height=480, units='px')
dev.off()
